guard 'livereload', :host => 'THEMENAME', :port => '35729' do
  watch(%r{.+\.(sass|css|js|jpg|jpeg|png|html?|php|inc)$})
end

guard 'compass',
  :configuration_file => "config.rb" do
  watch(%r{scss/.+\.s[ac]ss})
end
